#!/usr/bin/env python

import cgitb
import cgi
import sqlite3
import os
import Cookie


def print_class(x):
	print "<div class='dataInner'>"
	classColor = x[5]
	print "<div style='color:" + classColor + "'; >"
	print "<h2 id='individual-class-information-title'>" + str(x[1]) + "</h2>"
	if str(x[4])!="":
		print "<p class='individual-class-information-data'>Class time: " + str(x[4]) + "<br>"
	s = ""
	if str(x[3])!="":
		i = 0
		if x[3][0] == "[":
			i = 1
		while i<len(x[3]) - 2:
			if x[3][i]=="M" and x[3][i + 1]=="i":
				i += 22
			if x[3][i]==")":
				s += ", "
				i = i + 2
			if x[3][i]!="'" and x[3][i]!="(" and x[3][i]!="," and x[3][i]!=")":
				s+= x[3][i]
			i = i + 1
		print s

	if str(x[6])!="":
		print "<br>Instructor: " + str(x[6]) + "<br>"

	print "</p></div></div>"

	# Print everything into a list element formatted nicely

def print_class_name(x):
	print "<h2>" + str(x[1]) + "</h2>"


cgitb.enable()
class_form = cgi.FieldStorage()

conn = sqlite3.connect('classes.db')
c = conn.cursor()

c.execute('CREATE TABLE IF NOT EXISTS classes(id varchar(100) primary key, name varchar(100), userid varchar(100), days varchar(100), time varchar(10), color varchar(10), instructor varchar(100), notes varchar(200))')

try:	
	cookie_string = os.environ.get('HTTP_COOKIE')
	cookie = Cookie.SimpleCookie(cookie_string)
	userid = str(cookie['userid'].value)
except KeyError:
	print
	print "<h1>Please Enable Cookies to continue!</h1>"
	print "<a href='index.html'>Click here to Log In</a>"
	quit()
print


currentEntries = c.execute('SELECT * FROM classes WHERE userid=?', [userid]) # AND username = username
data = c.fetchall()


if len(data)==0:
	# print ''
	# print '<h2><a href="../new-class.html">Click here to add a class.</a></h2>'
	print '''
	
		<h1>No classes yet!</h1>
	'''
else:
	print '''
				</div>	

				<div class="class-information-main">
			


	'''

	for entry in data:
		#print "Hello world!"
		print_class(entry)

	print '''
				</div>	
			</div>	

				
	'''







